#pragma config(Sensor, in1,    gyro,           sensorGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include<GyroLib.c>

task main()
{
   GyroInit( gyro );

   while(true){
  	 	int theta = GyroGetAngle();
   		writeDebugStreamLine("%d : %d",c,theta);
   		wait1Msec(5);
	}
}
